<a href="https://colab.research.google.com/github/michaji/save_it/blob/master/Learning_Tensorflow1_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import sklearn as sk
import seaborn as sns
import tensorflow.compat.v1 as tf
tf.disable_eager_execution()
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
import os

In [ ]:
x = tf.Variable(34, name = 'x')
y = tf.Variable(12, name = 'y')
z = tf.Variable(45, name = 'z')
f = pow(x,3) + pow(x,2)*y +y*z

In [ ]:
with tf.Session() as sess:
  init = tf.global_variables_initializer()
  init.run()
  result = f.eval()
  print(result)

53716


In [ ]:
a1 = tf.constant(3)
a2 = a1 + 12
a3 = a2 - 8

In [ ]:
with tf.Session() as sess:
  init = tf.global_variables_initializer()
  init.run()
  a = a3.eval()
  print(a)

7


##**Matrix Operation**

###**Multiplication**

In [ ]:
m = tf.ones((20, 5))
n = tf.zeros((5, 20))
k = tf.ones((5,5))

y = tf.matmul(n,m) + k

with tf.Session() as sess:
  init = tf.global_variables_initializer()
  init.run()
  matrix = y.eval()


print(matrix)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


###**Determinant**

In [ ]:
arr = np.array([[2.0, 4.0, 6.6],
                [6.6, 8.2, 1.1],
                [7.4, 4.1, 2.9]])

v = tf.matrix_determinant(arr)

with tf.Session() as sess:
  out = v.eval()
  print(out)

-227.352


###**Inverse**

In [ ]:
inv_mat = tf.matrix_inverse(arr)

with  tf.Session() as sess:
  init = tf.global_variables_initializer()
  init.run()
  inv = inv_mat.eval()
  print(inv)

[[-0.08475844 -0.06800028  0.21869172]
 [ 0.04838312  0.18930997 -0.18192055]
 [ 0.14787642 -0.09412717  0.04398466]]


###**Transpose**

In [ ]:
trans = tf.matrix_transpose(inv_mat)
with tf.Session() as sess:
  init = tf.global_variables_initializer()
  init.run()
  trans_n = trans.eval()
  print(trans_n)

[[-0.08475844  0.04838312  0.14787642]
 [-0.06800028  0.18930997 -0.09412717]
 [ 0.21869172 -0.18192055  0.04398466]]


###**Diagonal Matrix**

In [ ]:
diag = tf.matrix_diag(inv_mat)
with tf.Session() as sess:
  init = tf.global_variables_initializer()
  init.run()
  diagonal =diag.eval()
  print(diagonal)

[[[-0.08475844  0.          0.        ]
  [ 0.         -0.06800028  0.        ]
  [ 0.          0.          0.21869172]]

 [[ 0.04838312  0.          0.        ]
  [ 0.          0.18930997  0.        ]
  [ 0.          0.         -0.18192055]]

 [[ 0.14787642  0.          0.        ]
  [ 0.         -0.09412717  0.        ]
  [ 0.          0.          0.04398466]]]


###**Argmax and Argmin**

**Argmax**

In [ ]:
dis = tf.argmax([3,20,4,15], name = 'dis')

with tf.Session() as sess:
  print(dis.eval())

1


**Argmin**

In [ ]:
arg = tf.argmin([4, 3, 20, 15], name = 'dis')

with tf.Session() as sess:
  print(dis.eval())

2


In [ ]:
arr

array([[2. , 4. , 6.6],
       [6.6, 8.2, 1.1],
       [7.4, 4.1, 2.9]])

In [ ]:
arg = tf.argmin(arr, axis=0)
with tf.Session() as sess:
  init = tf.global_variables_initializer()
  init.run()
  print(arg.eval())

[0 0 1]


###**Confusion Matrix**

In [ ]:
a = tf.random_uniform((90,),minval = 0, maxval=1)
b = tf.random_uniform((90,), minval =0, maxval =1)
pred = tf.round(a, 'pred')
y_true = tf.round(b, 'y_true')

confusion_mat = tf.confusion_matrix(pred, y_true, name= 'confusion_Matrix')
with tf.Session() as sess:
  init = tf.global_variables_initializer()
  init.run()
  print(confusion_mat.eval())

[[20 21]
 [28 21]]


###**Placeholders**

In [ ]:
A = tf.placeholder(tf.float32, shape = (None, 3))
B = A + 5

with tf.Session() as sess:
  b_val = B.eval(feed_dict = {A:[[1,2,3]]})
  b_val_u = B.eval(feed_dict = {A:[[4,5,6,], [7,8,9]]})

print(b_val)

[[6. 7. 8.]]
